//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nimap.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        [Required(ErrorMessage = "Required")]
        public int ProductId { get; set; }
        [Required(ErrorMessage="Required")]
        public string ProductName { get; set; }
        [Required(ErrorMessage = "Required")]
        public Nullable<int> CategoryId { get; set; }
        [Required(ErrorMessage="Required")]
        public string CategoryName { get; set; }
    }
}
